services:
  backend:
    build: ./app
    container_name: backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - backend_network
    
  frontend:
    build: ./finance_accounting
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - backend_network

  nginx:
    image: nginx:latest
    container_name: nginx-reverseproxy
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
